/* FluentGo offline curriculum: deterministic, goal-based and safe to cache. */
(function (global) {
  'use strict';

  const LEVELS = ['A1','A2','B1','B2'];
  const LEVEL_COPY = {
    A1:{label:'Khởi đầu',minutes:6,lead:'Nhận biết và dùng câu rất ngắn'},
    A2:{label:'Cơ bản',minutes:8,lead:'Xử lý tình huống quen thuộc'},
    B1:{label:'Trung cấp',minutes:11,lead:'Giao tiếp độc lập và giải thích ý'},
    B2:{label:'Nâng cao',minutes:14,lead:'Diễn đạt linh hoạt, có sắc thái'}
  };
  const TYPES = [
    ['listening','Nghe chọn ý'],['reading','Đọc hiểu'],['cloze','Điền từ'],['grammar','Ngữ pháp'],
    ['translation','Dịch theo ngữ cảnh'],['ordering','Sắp xếp câu'],['matching','Ghép nghĩa'],
    ['dictation','Chính tả'],['speaking','Phản xạ nói'],['writing','Viết ứng dụng']
  ];

  const goals = {
    general:{icon:'💬',name:'Giao tiếp cơ bản',englishName:'Everyday English',description:'Tự tin trong các tình huống đời sống hằng ngày',topics:['Chào hỏi và làm quen','Gia đình và bạn bè','Thói quen hằng ngày','Ăn uống','Mua sắm','Đi lại trong thành phố','Sức khỏe','Nhà cửa','Sở thích','Kế hoạch cuối tuần','Giải quyết vấn đề','Hội thoại tổng hợp'],englishTopics:['Meeting people','Family and friends','Daily routines','Food and drinks','Shopping','Getting around town','Health and appointments','Home and neighborhood','Hobbies and interests','Weekend plans','Solving everyday problems','Everyday conversations']},
    developer:{icon:'💻',name:'Tiếng Anh cho lập trình viên',englishName:'English for Developers',description:'Đọc tài liệu, trao đổi kỹ thuật và làm việc trong team quốc tế',topics:['Công cụ và môi trường','Đọc tài liệu','Mô tả bug','Git và code review','Daily stand-up','Ước lượng công việc','API và dữ liệu','Kiểm thử','Trao đổi với khách hàng','Thiết kế hệ thống','Phỏng vấn kỹ thuật','Demo sản phẩm'],englishTopics:['Tools and environments','Reading documentation','Describing bugs','Git and code review','Daily stand-ups','Estimating work','APIs and data','Software testing','Client communication','System design','Technical interviews','Product demos']},
    workplace:{icon:'💼',name:'Tiếng Anh công sở',englishName:'Workplace English',description:'Email, họp, thuyết trình và cộng tác chuyên nghiệp',topics:['Giới thiệu ở công ty','Lịch và cuộc hẹn','Email cơ bản','Họp nhóm','Báo cáo tiến độ','Yêu cầu hỗ trợ','Phản hồi chuyên nghiệp','Thuyết trình','Đàm phán','Quản lý dự án','Giải quyết xung đột','Tổng kết công việc'],englishTopics:['Meeting colleagues','Schedules and appointments','Writing emails','Team meetings','Progress updates','Asking for support','Professional feedback','Presentations','Negotiation','Project management','Resolving conflict','Reviewing results']},
    travel:{icon:'✈️',name:'Du lịch và định cư',englishName:'Travel English',description:'Chủ động từ sân bay đến các tình huống sinh hoạt ở nước ngoài',topics:['Sân bay','Nhập cảnh','Khách sạn','Hỏi đường','Phương tiện công cộng','Nhà hàng','Mua sắm','Y tế khẩn cấp','Tham quan','Giao lưu văn hóa','Xử lý sự cố','Lập kế hoạch chuyến đi'],englishTopics:['At the airport','Immigration','At the hotel','Asking for directions','Public transport','At a restaurant','Shopping abroad','Medical emergencies','Sightseeing','Cultural exchange','Travel problems','Planning a trip']},
    study:{icon:'🎓',name:'Học tập và du học',englishName:'Academic English',description:'Học trên lớp, làm bài, thuyết trình và sống ở môi trường quốc tế',topics:['Làm quen lớp học','Hỏi bài','Thời khóa biểu','Thư viện','Làm việc nhóm','Ghi chú bài giảng','Viết học thuật','Thuyết trình','Trao đổi với giảng viên','Thi và ôn tập','Đời sống sinh viên','Dự án cuối kỳ'],englishTopics:['Meeting classmates','Asking questions','Class schedules','Using the library','Group work','Taking lecture notes','Academic writing','Giving presentations','Talking to a lecturer','Exams and revision','Student life','Final projects']},
    service:{icon:'🤝',name:'Dịch vụ và bán hàng',englishName:'Customer Service English',description:'Tư vấn, phục vụ và xử lý khách hàng bằng tiếng Anh',topics:['Chào đón khách','Tìm hiểu nhu cầu','Giới thiệu sản phẩm','Giá và thanh toán','Đặt chỗ','Xác nhận đơn hàng','Hướng dẫn sử dụng','Tiếp nhận phàn nàn','Đổi trả','Đề xuất thêm','Chăm sóc sau bán','Tình huống tổng hợp'],englishTopics:['Welcoming customers','Understanding needs','Presenting products','Prices and payment','Making bookings','Confirming orders','Giving instructions','Handling complaints','Returns and exchanges','Making recommendations','After-sales support','Complete service scenarios']}
  };

  const lexicons = {
    general:[['greet','chào hỏi','I greet my neighbors every morning.','Tôi chào hàng xóm mỗi sáng.','/ɡriːt/ · verb','👋'],['introduce','giới thiệu','Let me introduce my friend.','Để tôi giới thiệu bạn của mình.','/ˌɪn.trəˈdjuːs/ · verb','🤝'],['relative','họ hàng','My relatives live nearby.','Họ hàng của tôi sống gần đây.','/ˈrel.ə.tɪv/ · noun','👨‍👩‍👧'],['supportive','hay giúp đỡ','My family is very supportive.','Gia đình tôi rất hay giúp đỡ.','/səˈpɔː.tɪv/ · adj','💛'],['routine','thói quen','This is my morning routine.','Đây là thói quen buổi sáng của tôi.','/ruːˈtiːn/ · noun','⏰'],['usually','thường xuyên','I usually walk to work.','Tôi thường đi bộ đến chỗ làm.','/ˈjuː.ʒu.ə.li/ · adv','🔁'],['ingredient','nguyên liệu','We need one more ingredient.','Chúng ta cần thêm một nguyên liệu.','/ɪnˈɡriː.di.ənt/ · noun','🥗'],['recommend','đề xuất','Can you recommend a dish?','Bạn có thể đề xuất một món không?','/ˌrek.əˈmend/ · verb','🍜'],['receipt','hóa đơn','May I have the receipt?','Cho tôi xin hóa đơn được không?','/rɪˈsiːt/ · noun','🧾'],['affordable','vừa túi tiền','This jacket is affordable.','Áo khoác này vừa túi tiền.','/əˈfɔː.də.bəl/ · adj','🛍️'],['direction','phương hướng','Could you give me directions?','Bạn có thể chỉ đường cho tôi không?','/dəˈrek.ʃən/ · noun','🧭'],['nearby','ở gần','Is there a bank nearby?','Có ngân hàng nào gần đây không?','/ˌnɪəˈbaɪ/ · adv','📍'],['appointment','cuộc hẹn','I have a doctor appointment.','Tôi có lịch hẹn bác sĩ.','/əˈpɔɪnt.mənt/ · noun','🩺'],['recover','hồi phục','I hope you recover soon.','Tôi mong bạn sớm hồi phục.','/rɪˈkʌv.ər/ · verb','💊'],['comfortable','thoải mái','The room is comfortable.','Căn phòng rất thoải mái.','/ˈkʌm.fə.tə.bəl/ · adj','🛋️'],['neighborhood','khu phố','Our neighborhood is quiet.','Khu phố của chúng tôi yên tĩnh.','/ˈneɪ.bə.hʊd/ · noun','🏘️'],['hobby','sở thích','Photography is my hobby.','Nhiếp ảnh là sở thích của tôi.','/ˈhɒb.i/ · noun','🎨'],['improve','cải thiện','Practice helps me improve.','Luyện tập giúp tôi cải thiện.','/ɪmˈpruːv/ · verb','📈'],['arrange','sắp xếp','Let us arrange a meeting.','Hãy sắp xếp một cuộc gặp.','/əˈreɪndʒ/ · verb','📅'],['available','rảnh; có sẵn','Are you available on Sunday?','Bạn rảnh vào Chủ nhật không?','/əˈveɪ.lə.bəl/ · adj','✅'],['issue','vấn đề','We can solve this issue.','Chúng ta có thể giải quyết vấn đề này.','/ˈɪʃ.uː/ · noun','🧩'],['apologize','xin lỗi','I apologize for the delay.','Tôi xin lỗi vì sự chậm trễ.','/əˈpɒl.ə.dʒaɪz/ · verb','🙏'],['respond','phản hồi','Please respond when you can.','Hãy phản hồi khi bạn có thể.','/rɪˈspɒnd/ · verb','💬'],['confident','tự tin','I feel more confident now.','Bây giờ tôi thấy tự tin hơn.','/ˈkɒn.fɪ.dənt/ · adj','🌟']],
    developer:[['repository','kho mã','Clone the repository first.','Hãy sao chép kho mã trước.','/rɪˈpɒz.ɪ.tər.i/ · noun','📦'],['environment','môi trường','Set up the development environment.','Thiết lập môi trường phát triển.','/ɪnˈvaɪ.rən.mənt/ · noun','🛠️'],['documentation','tài liệu','Read the API documentation.','Đọc tài liệu API.','/ˌdɒk.jə.menˈteɪ.ʃən/ · noun','📚'],['example','ví dụ','The example explains the method.','Ví dụ giải thích phương thức.','/ɪɡˈzɑːm.pəl/ · noun','🔎'],['reproduce','tái hiện','Can you reproduce the bug?','Bạn có thể tái hiện lỗi không?','/ˌriː.prəˈdjuːs/ · verb','🐞'],['unexpected','không mong đợi','We received an unexpected result.','Chúng tôi nhận kết quả không mong đợi.','/ˌʌn.ɪkˈspek.tɪd/ · adj','⚠️'],['branch','nhánh mã','Create a new branch.','Tạo một nhánh mới.','/brɑːntʃ/ · noun','🌿'],['review','xem xét','Please review my changes.','Vui lòng xem xét thay đổi của tôi.','/rɪˈvjuː/ · verb','👀'],['progress','tiến độ','I will share my progress.','Tôi sẽ chia sẻ tiến độ.','/ˈprəʊ.ɡres/ · noun','📈'],['blocker','trở ngại','This dependency is a blocker.','Phụ thuộc này là một trở ngại.','/ˈblɒk.ər/ · noun','🚧'],['estimate','ước lượng','We estimate two days.','Chúng tôi ước lượng hai ngày.','/ˈes.tɪ.meɪt/ · verb','⏳'],['scope','phạm vi','The scope has changed.','Phạm vi đã thay đổi.','/skəʊp/ · noun','🎯'],['endpoint','điểm cuối API','This endpoint returns users.','Điểm cuối này trả về người dùng.','/ˈend.pɔɪnt/ · noun','🔌'],['payload','dữ liệu gửi đi','Validate the request payload.','Hãy kiểm tra dữ liệu gửi đi.','/ˈpeɪ.ləʊd/ · noun','📨'],['coverage','độ bao phủ','Test coverage is improving.','Độ bao phủ kiểm thử đang tăng.','/ˈkʌv.ər.ɪdʒ/ · noun','🧪'],['assertion','câu kiểm chứng','This assertion should pass.','Câu kiểm chứng này phải đạt.','/əˈsɜː.ʃən/ · noun','✅'],['requirement','yêu cầu','Clarify the requirement.','Hãy làm rõ yêu cầu.','/rɪˈkwaɪə.mənt/ · noun','📋'],['feedback','phản hồi','The client gave useful feedback.','Khách hàng đã đưa phản hồi hữu ích.','/ˈfiːd.bæk/ · noun','💬'],['architecture','kiến trúc','The architecture supports scaling.','Kiến trúc hỗ trợ mở rộng.','/ˈɑː.kɪ.tek.tʃər/ · noun','🏗️'],['trade-off','sự đánh đổi','Explain the performance trade-off.','Giải thích sự đánh đổi hiệu năng.','/ˈtreɪd.ɒf/ · noun','⚖️'],['algorithm','thuật toán','Describe your algorithm clearly.','Hãy mô tả rõ thuật toán.','/ˈæl.ɡə.rɪ.ðəm/ · noun','🧠'],['complexity','độ phức tạp','Analyze the time complexity.','Phân tích độ phức tạp thời gian.','/kəmˈplek.sə.ti/ · noun','📊'],['demonstrate','trình diễn','I will demonstrate the feature.','Tôi sẽ trình diễn tính năng.','/ˈdem.ən.streɪt/ · verb','🎬'],['deploy','triển khai','We can deploy this afternoon.','Chúng ta có thể triển khai chiều nay.','/dɪˈplɔɪ/ · verb','🚀']],
    workplace:[['colleague','đồng nghiệp','My colleague joined the call.','Đồng nghiệp của tôi đã vào cuộc gọi.','/ˈkɒl.iːɡ/ · noun','👥'],['department','phòng ban','She works in our department.','Cô ấy làm ở phòng ban của chúng tôi.','/dɪˈpɑːt.mənt/ · noun','🏢'],['schedule','lịch trình','Please check my schedule.','Vui lòng xem lịch của tôi.','/ˈʃed.juːl/ · noun','📅'],['reschedule','đổi lịch','Can we reschedule the meeting?','Ta có thể đổi lịch họp không?','/ˌriːˈʃed.juːl/ · verb','🔄'],['attach','đính kèm','I attached the report.','Tôi đã đính kèm báo cáo.','/əˈtætʃ/ · verb','📎'],['regarding','về việc','I am writing regarding the order.','Tôi viết thư về đơn hàng.','/rɪˈɡɑː.dɪŋ/ · prep','✉️'],['agenda','chương trình họp','The agenda has three items.','Chương trình họp có ba mục.','/əˈdʒen.də/ · noun','📝'],['contribute','đóng góp','Everyone can contribute ideas.','Mọi người đều có thể đóng góp ý tưởng.','/kənˈtrɪb.juːt/ · verb','🙋'],['deadline','hạn chót','The deadline is Friday.','Hạn chót là thứ Sáu.','/ˈded.laɪn/ · noun','⏰'],['milestone','cột mốc','We reached a milestone.','Chúng tôi đã đạt một cột mốc.','/ˈmaɪl.stəʊn/ · noun','🏁'],['assist','hỗ trợ','Could you assist me?','Bạn có thể hỗ trợ tôi không?','/əˈsɪst/ · verb','🤲'],['resource','nguồn lực','We need another resource.','Chúng ta cần thêm nguồn lực.','/rɪˈzɔːs/ · noun','🧰'],['constructive','mang tính xây dựng','Her feedback was constructive.','Phản hồi của cô ấy mang tính xây dựng.','/kənˈstrʌk.tɪv/ · adj','💡'],['specific','cụ thể','Please be more specific.','Vui lòng cụ thể hơn.','/spəˈsɪf.ɪk/ · adj','🔍'],['highlight','nhấn mạnh','I will highlight the results.','Tôi sẽ nhấn mạnh kết quả.','/ˈhaɪ.laɪt/ · verb','📊'],['audience','khán giả','Know your audience.','Hãy hiểu khán giả của bạn.','/ˈɔː.di.əns/ · noun','🎤'],['negotiate','đàm phán','We need to negotiate the price.','Chúng ta cần đàm phán giá.','/nɪˈɡəʊ.ʃi.eɪt/ · verb','🤝'],['proposal','đề xuất','They accepted our proposal.','Họ đã chấp nhận đề xuất.','/prəˈpəʊ.zəl/ · noun','📄'],['priority','ưu tiên','Quality is our priority.','Chất lượng là ưu tiên của chúng tôi.','/praɪˈɒr.ə.ti/ · noun','⭐'],['coordinate','điều phối','I coordinate the project.','Tôi điều phối dự án.','/kəʊˈɔː.dɪ.neɪt/ · verb','🗂️'],['resolve','giải quyết','Let us resolve this concern.','Hãy giải quyết mối lo này.','/rɪˈzɒlv/ · verb','🧩'],['compromise','thỏa hiệp','We found a compromise.','Chúng tôi đã tìm được thỏa hiệp.','/ˈkɒm.prə.maɪz/ · noun','⚖️'],['achievement','thành tựu','This is a team achievement.','Đây là thành tựu của nhóm.','/əˈtʃiːv.mənt/ · noun','🏆'],['outcome','kết quả','The outcome was positive.','Kết quả rất tích cực.','/ˈaʊt.kʌm/ · noun','✅']],
    travel:[['boarding','lên máy bay','Boarding starts at nine.','Việc lên máy bay bắt đầu lúc chín giờ.','/ˈbɔː.dɪŋ/ · noun','✈️'],['luggage','hành lý','My luggage is too heavy.','Hành lý của tôi quá nặng.','/ˈlʌɡ.ɪdʒ/ · noun','🧳'],['passport','hộ chiếu','Here is my passport.','Đây là hộ chiếu của tôi.','/ˈpɑːs.pɔːt/ · noun','🛂'],['purpose','mục đích','What is the purpose of your visit?','Mục đích chuyến thăm là gì?','/ˈpɜː.pəs/ · noun','📋'],['reservation','đặt chỗ','I have a reservation.','Tôi có đặt chỗ.','/ˌrez.əˈveɪ.ʃən/ · noun','🏨'],['vacancy','phòng trống','Do you have any vacancies?','Bạn còn phòng trống không?','/ˈveɪ.kən.si/ · noun','🛏️'],['intersection','giao lộ','Turn right at the intersection.','Rẽ phải ở giao lộ.','/ˌɪn.təˈsek.ʃən/ · noun','🗺️'],['opposite','đối diện','The bank is opposite the park.','Ngân hàng đối diện công viên.','/ˈɒp.ə.zɪt/ · prep','📍'],['platform','sân ga','The train leaves from platform six.','Tàu rời sân ga số sáu.','/ˈplæt.fɔːm/ · noun','🚆'],['fare','giá vé','How much is the fare?','Giá vé bao nhiêu?','/feər/ · noun','🎫'],['menu','thực đơn','Could I see the menu?','Cho tôi xem thực đơn được không?','/ˈmen.juː/ · noun','🍽️'],['allergy','dị ứng','I have a nut allergy.','Tôi bị dị ứng hạt.','/ˈæl.ə.dʒi/ · noun','⚠️'],['souvenir','quà lưu niệm','I bought a small souvenir.','Tôi mua một món quà lưu niệm nhỏ.','/ˌsuː.vənˈɪər/ · noun','🎁'],['refund','hoàn tiền','Can I get a refund?','Tôi có thể được hoàn tiền không?','/ˈriː.fʌnd/ · noun','💳'],['emergency','khẩn cấp','Call this number in an emergency.','Gọi số này khi khẩn cấp.','/ɪˈmɜː.dʒən.si/ · noun','🚑'],['symptom','triệu chứng','Describe your symptoms.','Hãy mô tả triệu chứng.','/ˈsɪmp.təm/ · noun','🩺'],['landmark','địa danh','This temple is a famous landmark.','Ngôi đền này là địa danh nổi tiếng.','/ˈlænd.mɑːk/ · noun','🏛️'],['admission','vé vào cửa','Admission is free today.','Hôm nay vào cửa miễn phí.','/ədˈmɪʃ.ən/ · noun','🎟️'],['custom','phong tục','Respect local customs.','Hãy tôn trọng phong tục địa phương.','/ˈkʌs.təm/ · noun','🌏'],['appropriate','phù hợp','Is this clothing appropriate?','Trang phục này có phù hợp không?','/əˈprəʊ.pri.ət/ · adj','👕'],['delay','sự chậm trễ','The delay is two hours.','Chuyến bị trễ hai giờ.','/dɪˈleɪ/ · noun','⌛'],['lost','bị thất lạc','My wallet is lost.','Ví của tôi bị thất lạc.','/lɒst/ · adj','🔎'],['itinerary','lịch trình chuyến đi','Our itinerary is flexible.','Lịch trình của chúng tôi linh hoạt.','/aɪˈtɪn.ər.ər.i/ · noun','🗓️'],['destination','điểm đến','Tokyo is our destination.','Tokyo là điểm đến của chúng tôi.','/ˌdes.tɪˈneɪ.ʃən/ · noun','🧭']],
    study:[['classmate','bạn cùng lớp','My classmate is from Korea.','Bạn cùng lớp tôi đến từ Hàn Quốc.','/ˈklɑːs.meɪt/ · noun','👋'],['campus','khuôn viên trường','The campus is very large.','Khuôn viên trường rất lớn.','/ˈkæm.pəs/ · noun','🏫'],['assignment','bài tập','The assignment is due tomorrow.','Bài tập đến hạn ngày mai.','/əˈsaɪn.mənt/ · noun','📚'],['clarify','làm rõ','Could you clarify this point?','Thầy cô có thể làm rõ điểm này không?','/ˈklær.ɪ.faɪ/ · verb','❓'],['timetable','thời khóa biểu','Check your timetable.','Hãy xem thời khóa biểu.','/ˈtaɪmˌteɪ.bəl/ · noun','📅'],['lecture','bài giảng','The lecture starts at ten.','Bài giảng bắt đầu lúc mười giờ.','/ˈlek.tʃər/ · noun','🎓'],['borrow','mượn','May I borrow this book?','Tôi có thể mượn sách này không?','/ˈbɒr.əʊ/ · verb','📖'],['reference','tài liệu tham khảo','Use two references.','Hãy dùng hai tài liệu tham khảo.','/ˈref.ər.əns/ · noun','🔖'],['collaborate','cộng tác','We collaborate on the project.','Chúng tôi cộng tác trong dự án.','/kəˈlæb.ə.reɪt/ · verb','👥'],['contribution','sự đóng góp','Thank you for your contribution.','Cảm ơn sự đóng góp của bạn.','/ˌkɒn.trɪˈbjuː.ʃən/ · noun','🙌'],['summarize','tóm tắt','Summarize the main idea.','Hãy tóm tắt ý chính.','/ˈsʌm.ər.aɪz/ · verb','📝'],['concept','khái niệm','This concept is important.','Khái niệm này quan trọng.','/ˈkɒn.sept/ · noun','💡'],['citation','trích dẫn','Add a citation here.','Thêm trích dẫn ở đây.','/saɪˈteɪ.ʃən/ · noun','✍️'],['argument','luận điểm','Support your argument.','Hãy hỗ trợ luận điểm.','/ˈɑː.ɡjə.mənt/ · noun','📄'],['visual','hình ảnh trực quan','Use a clear visual.','Hãy dùng hình ảnh rõ ràng.','/ˈvɪʒ.u.əl/ · noun','📊'],['rehearse','diễn tập','Rehearse your presentation.','Hãy diễn tập bài thuyết trình.','/rɪˈhɜːs/ · verb','🎤'],['extension','gia hạn','May I request an extension?','Em có thể xin gia hạn không?','/ɪkˈsten.ʃən/ · noun','⏳'],['supervisor','người hướng dẫn','Meet your supervisor.','Hãy gặp người hướng dẫn.','/ˈsuː.pə.vaɪ.zər/ · noun','👩‍🏫'],['revise','ôn tập; chỉnh sửa','I need to revise tonight.','Tối nay tôi cần ôn tập.','/rɪˈvaɪz/ · verb','🔁'],['criteria','tiêu chí','Read the grading criteria.','Đọc tiêu chí chấm điểm.','/kraɪˈtɪə.ri.ə/ · noun','✅'],['accommodation','chỗ ở','Student accommodation is nearby.','Chỗ ở sinh viên ở gần đây.','/əˌkɒm.əˈdeɪ.ʃən/ · noun','🏠'],['society','câu lạc bộ','I joined the music society.','Tôi tham gia câu lạc bộ âm nhạc.','/səˈsaɪ.ə.ti/ · noun','🎵'],['research','nghiên cứu','Our research examines language.','Nghiên cứu xem xét ngôn ngữ.','/rɪˈsɜːtʃ/ · noun','🔬'],['finding','phát hiện','The findings are surprising.','Các phát hiện thật bất ngờ.','/ˈfaɪn.dɪŋ/ · noun','🔍']],
    service:[['welcome','chào đón','We welcome every customer.','Chúng tôi chào đón mọi khách hàng.','/ˈwel.kəm/ · verb','👋'],['assist','hỗ trợ','How may I assist you?','Tôi có thể hỗ trợ bạn thế nào?','/əˈsɪst/ · verb','🤝'],['preference','sở thích lựa chọn','What is your preference?','Bạn thích lựa chọn nào?','/ˈpref.ər.əns/ · noun','🎯'],['requirement','nhu cầu; yêu cầu','Tell me your requirements.','Hãy cho tôi biết nhu cầu.','/rɪˈkwaɪə.mənt/ · noun','📋'],['feature','tính năng','This feature saves time.','Tính năng này tiết kiệm thời gian.','/ˈfiː.tʃər/ · noun','✨'],['suitable','phù hợp','This option is suitable for you.','Lựa chọn này phù hợp với bạn.','/ˈsuː.tə.bəl/ · adj','✅'],['discount','giảm giá','This item has a discount.','Món này đang giảm giá.','/ˈdɪs.kaʊnt/ · noun','🏷️'],['payment','thanh toán','Your payment was successful.','Thanh toán của bạn đã thành công.','/ˈpeɪ.mənt/ · noun','💳'],['booking','đặt chỗ','I confirmed your booking.','Tôi đã xác nhận đặt chỗ.','/ˈbʊk.ɪŋ/ · noun','📅'],['availability','tình trạng còn hàng/chỗ','I will check availability.','Tôi sẽ kiểm tra tình trạng còn chỗ.','/əˌveɪ.ləˈbɪl.ə.ti/ · noun','🔎'],['confirm','xác nhận','Please confirm your address.','Vui lòng xác nhận địa chỉ.','/kənˈfɜːm/ · verb','📦'],['delivery','giao hàng','Delivery takes two days.','Giao hàng mất hai ngày.','/dɪˈlɪv.ər.i/ · noun','🚚'],['instruction','hướng dẫn','Follow these instructions.','Hãy làm theo hướng dẫn.','/ɪnˈstrʌk.ʃən/ · noun','📖'],['operate','vận hành','This button operates the machine.','Nút này vận hành máy.','/ˈɒp.ər.eɪt/ · verb','⚙️'],['complaint','lời phàn nàn','We received your complaint.','Chúng tôi đã nhận phàn nàn.','/kəmˈpleɪnt/ · noun','💬'],['inconvenience','sự bất tiện','We apologize for the inconvenience.','Chúng tôi xin lỗi vì sự bất tiện.','/ˌɪn.kənˈviː.ni.əns/ · noun','🙏'],['exchange','đổi hàng','You can exchange this item.','Bạn có thể đổi món hàng này.','/ɪksˈtʃeɪndʒ/ · verb','🔄'],['policy','chính sách','This is our return policy.','Đây là chính sách đổi trả.','/ˈpɒl.ə.si/ · noun','📜'],['upgrade','nâng cấp','Would you like an upgrade?','Bạn có muốn nâng cấp không?','/ˈʌp.ɡreɪd/ · noun','⬆️'],['bundle','gói sản phẩm','This bundle offers better value.','Gói này có giá trị tốt hơn.','/ˈbʌn.dəl/ · noun','🎁'],['satisfaction','sự hài lòng','Your satisfaction matters.','Sự hài lòng của bạn rất quan trọng.','/ˌsæt.ɪsˈfæk.ʃən/ · noun','😊'],['follow-up','việc theo dõi sau đó','I will send a follow-up email.','Tôi sẽ gửi email theo dõi.','/ˈfɒl.əʊ.ʌp/ · noun','✉️'],['solution','giải pháp','Let us find a solution.','Hãy cùng tìm giải pháp.','/səˈluː.ʃən/ · noun','🧩'],['professional','chuyên nghiệp','Stay calm and professional.','Hãy bình tĩnh và chuyên nghiệp.','/prəˈfeʃ.ən.əl/ · adj','🌟']]
  };

  function card(raw,topic,goalId,index) {
    return {word:raw[0],meaning:raw[1],example:raw[2],vi:raw[3],phonetic:raw[4],icon:raw[5],topic,goalId,id:goalId+'-word-'+index};
  }
  function options(correct,wrongA,wrongB) { return [correct,wrongA,wrongB]; }
  function rotate(values,amount) { return values.map((_,i)=>values[(i+amount)%values.length]); }
  function usageDistractors(word,phonetic) {
    const part=String(phonetic).split('·').pop().trim();
    if (part==='verb') return [`She ${word} is every day.`,`He can ${word}s it.`];
    if (part==='adj') return [`I ${word} the task.`,`She speaks ${word}ly it.`];
    if (part==='adv') return [`This is a ${word} plan.`,`We ${word} the report.`];
    return [`I ${word} every morning.`,`It is very ${word} today.`];
  }
  function buildUnit(goalId,level,unitIndex) {
    const goal=goals[goalId],topic=goal.topics[unitIndex],topicEn=goal.englishTopics[unitIndex],raw=lexicons[goalId],a=card(raw[unitIndex*2],topic,goalId,unitIndex*2),b=card(raw[unitIndex*2+1],topic,goalId,unitIndex*2+1);
    const distractA=raw[(unitIndex*2+5)%raw.length],distractB=raw[(unitIndex*2+11)%raw.length],alternateTopicA=goal.englishTopics[(unitIndex+3)%12],alternateTopicB=goal.englishTopics[(unitIndex+7)%12];
    const dialogue={
      A1:`Alex: ${a.example}\nMia: ${b.example}`,
      A2:`Alex: Can we talk about ${topicEn.toLowerCase()}?\nMia: Of course. ${a.example}\nAlex: Great. ${b.example}`,
      B1:`Alex: We need to deal with ${topicEn.toLowerCase()} today. ${a.example}\nMia: That makes sense. ${b.example}\nAlex: Good. Let's agree on the next step.`,
      B2:`Alex: Before we make a decision about ${topicEn.toLowerCase()}, we should clarify the key point. ${a.example}\nMia: I agree with that approach. ${b.example}\nAlex: Then let's consider the possible consequences before we proceed.`
    }[level];
    const passage={
      A1:`Sam is learning about ${topicEn.toLowerCase()}. ${a.example} ${b.example}`,
      A2:`Sam is in a familiar situation involving ${topicEn.toLowerCase()}. ${a.example} After that, ${b.example.charAt(0).toLowerCase()+b.example.slice(1)}`,
      B1:`Sam needs to handle a situation involving ${topicEn.toLowerCase()}. The first step is clear: ${a.example} Sam then adds another useful detail: ${b.example} This helps everyone understand what should happen next.`,
      B2:`During a discussion about ${topicEn.toLowerCase()}, Sam tries to be precise without slowing down the conversation. ${a.example} Sam then develops the point further: ${b.example} By combining a clear request with relevant context, the exchange becomes more effective.`
    }[level];
    const wrongA=usageDistractors(a.word,a.phonetic),wrongB=usageDistractors(b.word,b.phonetic),grammarFocus={A1:'basic word order',A2:'questions and everyday verb forms',B1:'linking ideas and explaining reasons',B2:'precision, stance and nuanced responses'}[level];
    const exercises=[];
    const push=(type,variant,data)=>exercises.push(Object.assign({id:[goalId,level,unitIndex+1,type,variant].join('-'),goalId,level,difficulty:level,unit:unitIndex,topic,topicEn,type,typeLabel:TYPES.find(t=>t[0]===type)[1]},data));
    push('listening',1,{audio:dialogue,question:'What is the conversation mainly about?',options:rotate([topicEn,alternateTopicA,alternateTopicB],unitIndex%3),answer:topicEn,explanation:`Đoạn hội thoại tập trung vào chủ đề “${topic}”.`});
    push('listening',2,{audio:dialogue,question:'Which key word or phrase do you hear?',options:rotate([b.word,distractA[0],distractB[0]],(unitIndex+1)%3),answer:b.word,explanation:`Bạn nghe thấy “${b.word}” trong câu: “${b.example}”`});
    push('reading',1,{title:topicEn,passage,question:'What is the passage mainly about?',options:rotate([topicEn,alternateTopicA,alternateTopicB],(unitIndex+2)%3),answer:topicEn,explanation:`Ý chính là “${topic}”.`});
    push('reading',2,{title:`${topicEn}: a short scenario`,passage,question:'Which statement is mentioned in the passage?',options:rotate([b.example,distractA[2],distractB[2]],unitIndex%3),answer:b.example,explanation:`Câu “${b.example}” xuất hiện trực tiếp trong bài.`});
    push('cloze',1,{question:a.example.replace(new RegExp(a.word,'i'),'_____'),options:rotate([a.word,distractA[0],distractB[0]],unitIndex%3),answer:a.word,explanation:`Điền “${a.word}”: ${a.meaning}.`});
    push('cloze',2,{question:b.example.replace(new RegExp(b.word,'i'),'_____'),options:rotate([b.word,distractA[0],distractB[0]],(unitIndex+1)%3),answer:b.word,explanation:`Điền “${b.word}”: ${b.meaning}.`});
    push('grammar',1,{question:`Which sentence uses “${a.word}” correctly?`,options:rotate([a.example,wrongA[0],wrongA[1]],unitIndex%3),answer:a.example,explanation:`Trọng tâm ${level}: ${grammarFocus}. Câu đúng dùng “${a.word}” đúng vị trí và dạng từ.`});
    push('grammar',2,{question:`Which sentence uses “${b.word}” correctly?`,options:rotate([b.example,wrongB[0],wrongB[1]],(unitIndex+1)%3),answer:b.example,explanation:`Câu đúng là “${b.example}”`});
    push('translation',1,{question:a.vi,options:rotate([a.example,`We never use ${a.word}.`,b.example],unitIndex%3),answer:a.example,explanation:'Bản dịch giữ đúng nghĩa và ngữ cảnh.'});
    push('translation',2,{question:b.vi,options:rotate([b.example,a.example,`They did not understand the topic.`],(unitIndex+2)%3),answer:b.example,explanation:'Bản dịch đúng dùng cụm từ trọng tâm của bài.'});
    push('ordering',1,{question:`Put the words in the correct order: ${a.example.replace(/[.!?]/g,'').split(' ').reverse().join(' / ')}`,options:rotate([a.example,wrongA[0],b.example],unitIndex%3),answer:a.example,explanation:'Trật tự câu đúng giúp người nghe nhận ra chủ ngữ, hành động và thông tin bổ sung.'});
    push('ordering',2,{question:`Put the words in the correct order: ${b.example.replace(/[.!?]/g,'').split(' ').reverse().join(' / ')}`,options:rotate([b.example,a.example,wrongB[0]],(unitIndex+1)%3),answer:b.example,explanation:'Đọc lại câu hoàn chỉnh theo cụm, không đọc từng từ rời rạc.'});
    push('matching',1,{question:`What does “${a.word}” mean in Vietnamese?`,options:rotate([a.meaning,distractA[1],distractB[1]],unitIndex%3),answer:a.meaning,explanation:`${a.word} = ${a.meaning}.`});
    push('matching',2,{question:`What does “${b.word}” mean in Vietnamese?`,options:rotate([b.meaning,distractA[1],distractB[1]],(unitIndex+1)%3),answer:b.meaning,explanation:`${b.word} = ${b.meaning}.`});
    push('dictation',1,{audio:a.example,question:'Which sentence do you hear?',options:rotate([a.example,a.example.replace(a.word,distractA[0]),b.example],unitIndex%3),answer:a.example,explanation:'Nghe lại và chú ý từ trọng tâm, trọng âm và âm cuối.'});
    push('dictation',2,{audio:b.example,question:'Which sentence do you hear?',options:rotate([b.example,b.example.replace(b.word,distractB[0]),a.example],(unitIndex+2)%3),answer:b.example,explanation:'So sánh từng cụm âm thanh thay vì dịch sang tiếng Việt.'});
    push('speaking',1,{target:a.example,vi:a.vi,question:`Say the sentence naturally. Focus on “${a.word}”.`});
    push('speaking',2,{target:b.example,vi:b.vi,question:`Say the sentence, then make your own example with “${b.word}”.`});
    push('writing',1,{title:`Write about ${topicEn}`,instruction:`Write ${level==='A1'?'3–5 clear sentences':'one connected paragraph'} about ${topicEn.toLowerCase()}. Use “${a.word}” and “${b.word}”.`,chips:[a.example,b.example,`In this situation...`],minWords:{A1:12,A2:25,B1:45,B2:70}[level]});
    push('writing',2,{title:`Respond in a ${topicEn.toLowerCase()} situation`,instruction:`Write a useful English response. Include the main point, a reason and the next step.`,chips:[`I would like to...`,`The main point is...`,`Next, we can...`],minWords:{A1:12,A2:25,B1:45,B2:70}[level]});
    return {id:`${goalId}-${level}-unit-${unitIndex+1}`,number:unitIndex+1,title:topic,englishTitle:topicEn,description:`${LEVEL_COPY[level].lead} trong chủ đề ${topic.toLowerCase()}.`,cards:[a,b],exercises,guidebook:{outcomes:[`Understand a short ${topicEn.toLowerCase()} exchange`,`Use “${a.word}” and “${b.word}” in context`,`Respond without translating every word`],keyPhrases:[a.example,b.example],grammar:grammarFocus},lessons:[
      [`Key phrases: ${topicEn}`,'GUIDEBOOK'],[`Listen: ${topicEn}`,'DIALOGUE'],[`Read: ${topicEn}`,'STORY'],[`Grammar in action`,'PRACTICE'],[`Speak and write`,'PRODUCTION'],[`Mastery check`,'CHECKPOINT']
    ].map((lesson,i)=>({id:`${goalId}:${level}:${unitIndex}:${i}`,title:lesson[0],type:lesson[1],minutes:LEVEL_COPY[level].minutes+(i%3)}))};
  }

  const roadmaps={},exerciseBank=[];
  Object.keys(goals).forEach(goalId=>{
    roadmaps[goalId]={};
    LEVELS.forEach(level=>{
      roadmaps[goalId][level]=goals[goalId].topics.map((_,unitIndex)=>buildUnit(goalId,level,unitIndex));
      roadmaps[goalId][level].forEach(unit=>exerciseBank.push.apply(exerciseBank,unit.exercises));
    });
  });

  function getRoadmap(goalId,level) { return roadmaps[goalId]?.[level]||roadmaps.general.A1; }
  function getTopics(goalId) { return (goals[goalId]||goals.general).topics.slice(); }
  function getVocabulary(goalId,level,topic) {
    const units=getRoadmap(goalId,level),selected=topic&&topic!=='all'?units.filter(unit=>unit.title===topic):units;
    return selected.reduce((cards,unit)=>cards.concat(unit.cards.map(value=>Object.assign({},value,{level}))),[]);
  }
  function getExercises(goalId,level,type,topic) {
    return exerciseBank.filter(item=>item.goalId===(goals[goalId]?goalId:'general')&&item.level===(LEVELS.includes(level)?level:'A1')&&(!type||type==='all'||item.type===type)&&(!topic||topic==='all'||item.topic===topic));
  }
  function toPracticeDeck(goalId,level,type,topic) {
    if (type==='vocabulary') return getVocabulary(goalId,level,topic);
    return getExercises(goalId,level,type,topic).map(item=>{
      if (type==='listening') { const opts=item.options; return {audio:item.audio,question:item.question,options:opts,correct:opts.indexOf(item.answer),explanation:item.explanation,topic:item.topic,id:item.id}; }
      if (type==='reading') { const opts=item.options; return {title:item.title,passage:item.passage,question:item.question,options:opts,correct:opts.indexOf(item.answer),explanation:item.explanation,topic:item.topic,id:item.id}; }
      if (type==='speaking') return {target:item.target,vi:item.vi,topic:item.topic,id:item.id};
      if (type==='writing') return {title:item.title,instruction:item.instruction,chips:item.chips,minWords:item.minWords,topic:item.topic,id:item.id};
      return item;
    });
  }

  global.FLUENTGO_CURRICULUM={version:'2026.08-content-v2',levels:LEVELS,levelCopy:LEVEL_COPY,types:TYPES,goals,roadmaps,exerciseBank,getRoadmap,getTopics,getVocabulary,getExercises,toPracticeDeck,stats:{goals:Object.keys(goals).length,levels:LEVELS.length,topics:72,curatedPhrases:144,units:Object.keys(goals).length*LEVELS.length*12,lessons:Object.keys(goals).length*LEVELS.length*12*6,exerciseVariants:exerciseBank.length,exercises:exerciseBank.length,types:TYPES.length}};
})(window);
